# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: 
      - main
    paths:
      - "test_folder/**.py"
      - "test_folder/**"
      - "test_folder"

jobs:
  example-workflow:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test_folder
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Run formatting on the code using Black
        uses: rickstaa/action-black@v1

      - name: Test with pytest
        run: pytest
